name: dev-card

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    devcard:
        runs-on: ubuntu-latest
        steps:
            - name: devcard
              uses: dailydotdev/action-devcard@2.1.0
              with:
                  devcard_id: ${{ secrets.DEVCARD_ID }}
                  commit_branch: main
                  commit_filename: images/devcard.svg
                  commit_message: "updated daily.dev card"
