name: recent-activities

on:
    schedule:
        - cron: "*/30 * * * *"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: jamesgeorge007/github-activity-readme@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
              with:
                  MAX_LINES: 5
                  COMMIT_MSG: "updated recent activities"
